### ISSUE TITLE
[CONS BLOG] [TRACKING] Add multiple authors to posts once #182 is closed

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#586]
Posts needing multiple authors added once #182 is resolved:

- [ ] https://quansight.com/post/a-year-in-review-quansight-s-contributions-to-pytorch-in-2021 -- Mario Lezcano
- [ ] https://quansight.com/post/robust-predictions-and-increased-interpretability-through-domain-directed-modeling -- Rob Zinkov, Brian Skinn, Eric Kelly
- [ ] [Why We Are Excited About JupyterLab 3.0 Dynamic Extensions!](https://quansight.com/post/why-we-are-excited-about-jupyterlab-3-0-dynamic-extensions) -- Tony Fast, Gonzalo Peña-Castellanos, Eric Charles, Eric Kelly
- [ ] *[Nebari post, publication impending]*
- [ ] [RAPIDS cuCIM: Porting scikit-image Code to the GPU](https://quansight.com/post/rapids-cucim-porting-scikit-image-code-to-the-gpu) -- Gregory R. Lee (now at NVIDIA) & Gigon Bae (NVIDIA)
